# Starship prompt configuration template

add_newline = false

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"

[directory]
truncation_length = 3

[git_branch]

[nodejs]
format = "via [â¬¢ $version](bold green) "

[python]
format = "via [ğŸ $version]($style) [$virtualenv]($style) "
detect_extensions = ["py"]
style = "bold blue"

[nix_shell]
format = "via [$symbol$state( $name)]($style) "
symbol = "â„ï¸ "
style = "bold blue"

[aws]
format = "on [$symbol $profile]($style) "
symbol = "â˜ï¸ "
style = "bold yellow"
disabled = false

[azure]
format = "on [$symbol $subscription]($style) "
symbol = "â˜ï¸ "
style = "bold blue"
disabled = false
